### ISSUE TITLE
Transfer tiran/instructlab-quantize to instructlab org

### ISSUE THREAD

**Issue by tiran** [instructlab/community#267]
I would like to transfer https://github.com/tiran/instructlab-quantize from my personal account to the instructlab organization. The repository contains a new package with pre-build binaries for InstructLab CLI. You can find more information in the ticket https://github.com/instructlab/instructlab/issues/438 and pull request https://github.com/instructlab/instructlab/pull/1017 .

## TODO

- [ ] transfer repository from my personal account to instructlab
- [ ] update URLs in pyproject.toml
- [ ] add boiler plate to repository
   - CoC
   - SECURITY.md
   - mergify rules
- [ ] configure branch protection
- [ ] change trusted publisher settings in PyPI
- [ ] change trusted publisher settings in Test PyPI

**Comment by russellb** [comment]
Do you mind if I transfer this issue to the `dev-docs` repository? That's where I envision handling technical governance topics like this.
